package com.simats.netadaptive.data.firebase

import android.util.Log
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.FieldValue

/**
 * FirestoreManager handles Cloud Firestore operations.
 */
class FirestoreManager {

    private val firestore = FirebaseFirestore.getInstance()
    private val auth = FirebaseAuth.getInstance()
    private val TAG = "FirestoreManager"

    /**
     * Verifies Firestore connection by writing a test document.
     * Path: users/{uid}/test/{autoGeneratedId}
     */
    fun testFirestoreConnection() {
        Log.i(TAG, "testFirestoreConnection: STARTING TEST...")
        val currentUser = auth.currentUser
        if (currentUser == null) {
            Log.e(TAG, "testFirestoreConnection: User is not authenticated. Cannot write to Firestore.")
            return
        }

        val uid = currentUser.uid
        val testData = hashMapOf(
            "message" to "Firestore Connected",
            "timestamp" to FieldValue.serverTimestamp()
        )

        Log.d(TAG, "testFirestoreConnection: Starting write operation for user: $uid")

        firestore.collection("users")
            .document(uid)
            .collection("test")
            .add(testData)
            .addOnSuccessListener { documentReference ->
                Log.d(TAG, "testFirestoreConnection: Successfully connected! Document created with ID: ${documentReference.id}")
            }
            .addOnFailureListener { e ->
                Log.e(TAG, "testFirestoreConnection: Failed to write test document to Firestore", e)
            }
    }
}
